language: csharp

sudo: false  # use the new container-based Travis infrastructure 


before_install:
  - chmod +x build.sh
 
  matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet : 2.1.300
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet : 2.1.300
      dist: trusty
      sudo: required
      
script: 
  - ./build.sh All
