language: csharp
#sudo: required
sudo: false
dist: trusty # Ubuntu 14.04
mono: 4.5
dotnet : 2.1.403
addons:
  apt:
    packages:
      - libunwind8

before_install:
 - dotnet restore build.proj

script:
 - dotnet fake -v build

branches:
  except:
    - gh-pages