language: csharp
#sudo: required
sudo: false
dist: trusty # Ubuntu 14.04

matrix:
  include:
    - dotnet: 2.1.403
      mono: none
    - mono: latest

before_install:

 - dotnet restore build.proj


script:
 - dotnet fake build --target Linux

branches:
  except:
    - gh-pages
    - developer
    