image: 
  - Ubuntu
  - Visual Studio 2019

init:
  - git config --global core.autocrlf input

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
  - cmd: build.cmd
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - sh: sudo ./build.sh -t Linux

test: off
version: 0.0.1.{build}

branches:
  only:
    - master
    - developer

artifacts:
  - path: bin
    name: bin
