image: 
  - Visual Studio 2019
  - Ubuntu

init:
  - git config --global core.autocrlf input

for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - sh: build.sh -t Linux

-
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
  - cmd: build.cmd

test: off
version: 0.0.1.{build}

branches:
  only:
    - master
    - developer

artifacts:
  - path: bin
    name: bin
